### ISSUE TITLE
项目是停滞了吗

### ISSUE THREAD

**Issue by kuqilin** [RainySoft-Team/RainyOS#11]
我看你们好久没上传代码了，QQ我也没登进去看，停下来了吗？

**Comment by Rainy101112** [comment]
是的，在重构MM，但是我不会搞（，所以请了min0911大神暑假帮我修MM
目前已经在b18版本了，只不过仓库很久没有动过而已

**Comment by kuqilin** [comment]
蛙趣，min0911耶
